notation = input('Digite algo: ')
print('São número? ', notation.isnumeric())
print('São letra? ', notation.isalpha())
print('São números ou letras? ', notation.isalnum())
print('Está maiúsculo? ', notation.isupper())
print('Está minúsculo? ', notation.islower())
print('Só tem espaços?', notation.isspace())
print('Por fim, o tipo de {} é {}'.format(notation, type(notation)))